# Rewrite gff for processing with pipeline

In [1]:
import pandas as pd

In [ ]:
# Read gff file

gff = pd.read_csv('MGRFG5_1_Cba_WT_1_reference.gff3', sep='\t', comment='#', header=None)
gff = gff.loc[gff[0] =='contig_1']
gff

/tmp/ipykernel_2652208/3123858904.py:3: DtypeWarning: Columns (1,2,5,6,7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  gff = pd.read_csv('MGRFG5_1_Cba_WT_1_reference.gff3', sep='\t', comment='#', header=None)

,0,1,2,3,4,5,6,7,8
0,contig_1,Bakta,region,1.0,4531226.0,.,+,.,ID=contig_1;Name=contig_1
1,contig_1,Pyrodigal,CDS,1.0,1425.0,.,+,0,ID=FKEOJE_00001;Name=chromosomal replication i...
2,contig_1,Pyrodigal,CDS,1453.0,1890.0,.,+,0,ID=FKEOJE_00002;Name=protein-tyrosine-phosphat...
3,contig_1,Pyrodigal,CDS,1902.0,2618.0,.,+,0,ID=FKEOJE_00003;Name=Uroporphyrin-III C/tetrap...
4,contig_1,Pyrodigal,CDS,2663.0,3298.0,.,-,0,ID=FKEOJE_00004;Name=Peptidoglycan-binding pro...
...,...,...,...,...,...,...,...,...,...
4051,contig_1,Pyrodigal,CDS,4527481.0,4528533.0,.,+,0,ID=FKEOJE_04040;Name=bifunctional diaminohydro...
4052,contig_1,Pyrodigal,CDS,4528526.0,4529128.0,.,+,0,ID=FKEOJE_04041;Name=Putative hydrolase of the...
4053,contig_1,Pyrodigal,CDS,4529129.0,4529992.0,.,+,0,ID=FKEOJE_04042;Name=Uncharacterized membrane ...
4054,contig_1,Pyrodigal,CDS,4529992.0,4530606.0,.,+,0,ID=FKEOJE_04043;Name=Impact N-terminal domain-...
4055,contig_1,Pyrodigal,CDS,4530590.0,4531096.0,.,-,0,ID=FKEOJE_04044;Name=Thioesterase;locus_tag=FK...

In [5]:
gff[8] = gff[8] + ';gene_biotype=' + gff[2]
gff

,0,1,2,3,4,5,6,7,8
0,contig_1,Bakta,region,1.0,4531226.0,.,+,.,ID=contig_1;Name=contig_1;gene_biotype=region
1,contig_1,Pyrodigal,CDS,1.0,1425.0,.,+,0,ID=FKEOJE_00001;Name=chromosomal replication i...
2,contig_1,Pyrodigal,CDS,1453.0,1890.0,.,+,0,ID=FKEOJE_00002;Name=protein-tyrosine-phosphat...
3,contig_1,Pyrodigal,CDS,1902.0,2618.0,.,+,0,ID=FKEOJE_00003;Name=Uroporphyrin-III C/tetrap...
4,contig_1,Pyrodigal,CDS,2663.0,3298.0,.,-,0,ID=FKEOJE_00004;Name=Peptidoglycan-binding pro...
...,...,...,...,...,...,...,...,...,...
4051,contig_1,Pyrodigal,CDS,4527481.0,4528533.0,.,+,0,ID=FKEOJE_04040;Name=bifunctional diaminohydro...
4052,contig_1,Pyrodigal,CDS,4528526.0,4529128.0,.,+,0,ID=FKEOJE_04041;Name=Putative hydrolase of the...
4053,contig_1,Pyrodigal,CDS,4529129.0,4529992.0,.,+,0,ID=FKEOJE_04042;Name=Uncharacterized membrane ...
4054,contig_1,Pyrodigal,CDS,4529992.0,4530606.0,.,+,0,ID=FKEOJE_04043;Name=Impact N-terminal domain-...
4055,contig_1,Pyrodigal,CDS,4530590.0,4531096.0,.,-,0,ID=FKEOJE_04044;Name=Thioesterase;locus_tag=FK...

In [ ]:
set(gff[2].tolist()) # replace all types with gene except for region and regulatory region

{'CDS', 'ncRNA', 'rRNA', 'region', 'regulatory_region', 'tRNA', 'tmRNA'}

In [15]:
gff.replace(['CDS', 'ncRNA', 'rRNA', 'tRNA', 'tmRNA'], 'gene', inplace=True)
gff

,0,1,2,3,4,5,6,7,8
0,contig_1,Bakta,region,1.0,4531226.0,.,+,.,ID=contig_1;Name=contig_1;gene_biotype=region
1,contig_1,Pyrodigal,gene,1.0,1425.0,.,+,0,ID=FKEOJE_00001;Name=chromosomal replication i...
2,contig_1,Pyrodigal,gene,1453.0,1890.0,.,+,0,ID=FKEOJE_00002;Name=protein-tyrosine-phosphat...
3,contig_1,Pyrodigal,gene,1902.0,2618.0,.,+,0,ID=FKEOJE_00003;Name=Uroporphyrin-III C/tetrap...
4,contig_1,Pyrodigal,gene,2663.0,3298.0,.,-,0,ID=FKEOJE_00004;Name=Peptidoglycan-binding pro...
...,...,...,...,...,...,...,...,...,...
4051,contig_1,Pyrodigal,gene,4527481.0,4528533.0,.,+,0,ID=FKEOJE_04040;Name=bifunctional diaminohydro...
4052,contig_1,Pyrodigal,gene,4528526.0,4529128.0,.,+,0,ID=FKEOJE_04041;Name=Putative hydrolase of the...
4053,contig_1,Pyrodigal,gene,4529129.0,4529992.0,.,+,0,ID=FKEOJE_04042;Name=Uncharacterized membrane ...
4054,contig_1,Pyrodigal,gene,4529992.0,4530606.0,.,+,0,ID=FKEOJE_04043;Name=Impact N-terminal domain-...
4055,contig_1,Pyrodigal,gene,4530590.0,4531096.0,.,-,0,ID=FKEOJE_04044;Name=Thioesterase;locus_tag=FK...

In [16]:
# Write to output

gff.to_csv('MGRFG5_1_Cba_WT_1_reference_adjusted.gff3', sep='\t', header=False, index=False)

Hereafter, the comments from the original gff3 file will be added to the top of the file again.